id: I34A94762
legacy_id: P003216
ocr_import_info:
  bdrc_scan_id: W8LS15752
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T15:59:29'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:27:59.713865+00:00'
last_modified: 2022-09-04 11:28:03.879731
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS15752
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS15752
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བོད་ཀྱི་ཀ་དཔེ་དབུ་ཅན་དབུ་མེད།
statistics:
  ocr_word_mean_confidence_index: 0.74276264907669
  ocr_word_median_confidence_index: 0.8799999952316284
quality: null
bases:
  I8LS15781:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS15781
      total_pages: 14
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS15781.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.74276264907669
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
