id: I34A94762
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T15:59:37+00:00'
last_modified: '2022-06-07T18:27:02.926091+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS15752
  title: བོད་ཀྱི་ཀ་དཔེ་དབུ་ཅན་དབུ་མེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7296':
      image_group_id: I8LS15781
      title: ''
      total_pages: 14
      order: 1
      base_file: 7296.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
